### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by adityamoon** [grelleum/youtube-network-automation#3] opened 2018-04-23 09:24 UTC
hi greg,

thanks for the scripts. I am facing one issue where only last command in commands.txt is getting parsed and saved in the file.

**Comment by grelleum** [comment] 2018-04-23 13:42
Most likely the problem is that you are either executing the command outside of the loop, or you are saving the output of the command outside of the loop.

Consider the following code:

```commands = ['show clock', 'show interfaces', 'show version']
for command in commands:
    print('*** Inside the loop ***')
    print('***', command, '***')
print('### outside the loop ###')
print('###', command, '###')
```

Here is what the output of that code looks like:
```*** Inside the loop ***
*** show clock ***
*** Inside the loop ***
*** show interfaces ***
*** Inside the loop ***
*** show version ***
### outside the loop ###
### show version ###
```

Notice that the print statements that are indented each run three times, once for each command.
Notice that the print statements that have the same indentation as the `for command in commands:` are not considered part of that `for` loop and only are executed once, after the loop completes.  The command printed is the last value that was assigned to command before the loop completed.

Please let me know if that helps.   If you need futher assitance, please post your code and the output using markdown to denote the code.
https://guides.github.com/features/mastering-markdown/

**Closed as completed** 2018-08-22 10:53 UTC
